services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/s3cr3t
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - "${HOME}/neo4j/data:/data"
      - "${HOME}/neo4j/logs:/logs"
      - "${HOME}/neo4j/import:/var/lib/neo4j/import"
      - "${HOME}/neo4j/plugins:/plugins"
